GET http://localhost:5180/games

###
GET http://localhost:5180/games/1

###
POST http://localhost:5180/games
Content-Type: application/json

{
 "name": "Minecraft",
 "genreid": 5,
 "Price": 19.99,
 "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5180/games/1
Content-Type: application/json

{
    "id": 1,
    "name": "Street Figher II Evolution",
    "genreid": 1,
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5180/games/7

###
POST http://localhost:5180/users
Content-Type: application/json

{
 "name": "testt",
 "email": "test@test.com",
 "password": "test123"
}